-- Migration 007: Seed entity aliases
-- Uses ON CONFLICT DO NOTHING to be idempotent

INSERT INTO entity_aliases (canonical, alias) VALUES
  ('stripe', 'payment'),
  ('stripe', 'checkout'),
  ('stripe', 'pricing'),
  ('stripe', 'invoice'),
  ('stripe', 'billing'),
  ('stripe', 'subscription'),
  ('anthropic', 'claude'),
  ('anthropic', 'ai'),
  ('anthropic', 'llm'),
  ('anthropic', 'artificial intelligence'),
  ('supabase', 'database'),
  ('supabase', 'postgres'),
  ('supabase', 'postgresql'),
  ('supabase', 'db'),
  ('supabase', 'auth'),
  ('github', 'git'),
  ('github', 'repository'),
  ('github', 'repo'),
  ('github', 'version control'),
  ('github', 'source code'),
  ('vercel', 'deployment'),
  ('vercel', 'hosting'),
  ('vercel', 'serverless'),
  ('vercel', 'edge functions'),
  ('react', 'frontend'),
  ('react', 'ui'),
  ('react', 'component'),
  ('react', 'jsx'),
  ('react', 'tsx'),
  ('typescript', 'ts'),
  ('typescript', 'type'),
  ('typescript', 'typing'),
  ('javascript', 'js'),
  ('javascript', 'node'),
  ('javascript', 'nodejs'),
  ('css', 'styling'),
  ('css', 'tailwind'),
  ('css', 'design'),
  ('testing', 'test'),
  ('testing', 'vitest'),
  ('testing', 'unit test'),
  ('testing', 'integration test'),
  ('api', 'endpoint'),
  ('api', 'rest'),
  ('api', 'http'),
  ('api', 'route'),
  ('mcp', 'model context protocol'),
  ('mcp', 'tools'),
  ('mcp', 'server'),
  ('email', 'resend'),
  ('email', 'newsletter'),
  ('email', 'mail'),
  ('pocketbase', 'pb'),
  ('pocketbase', 'local database'),
  ('pocketbase', 'sqlite')
ON CONFLICT (canonical, alias) DO NOTHING;

-- Seed default settings
INSERT INTO settings (key, value) VALUES
  ('schema_version', '1'),
  ('business_name', ''),
  ('support_email', ''),
  ('timezone', 'UTC'),
  ('currency', 'USD')
ON CONFLICT (key) DO NOTHING;
